anchor_1: &job_defaults
  working_directory: ~/stylelint-config
  docker:
    - image: ptsecurity/node-container:0.0.1

version: 2
jobs:
  build:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: System information
          command: |
            echo "Node.js $(node -v)"
            echo "npm $(npm -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install npm packages
          command: npm -v && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

workflows:
  version: 2
  default_workflow:
    jobs:
      - build
